# Generated by Django 5.2.12 on 2026-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia', models.CharField(max_length=5)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('datas', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('enviado_whatsapp', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
